rails_5_essentials/exercise_files/Chapter_15/15_07/simple_cms/config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  get 'demo/escape_output'

  # default route
  # may go away in future versions of Rails
  # get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails_5_essentials/exercise_files/Chapter_15/15_07/simple_cms/app/views/layouts/_navigation.html.erb
<% subjects ||= [] %>
<ul>
<% subjects.each do |subject| %>
  <li>
    <%= subject.name %>
    <ul>
    <% subject.pages.visible.sorted.each do |page| %>
      <li><%= link_to_unless_current(page.name, public_show_path(page.permalink)) %></li>
    <% end %>
    </ul>
  </li>
  <% end %>
</ul>

rails_5_essentials/exercise_files/Chapter_15/15_07/simple_cms/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple CMS: <%= @page_title || "Admin Area" %></title>
    <%= stylesheet_link_tag('admin', :media => 'all') %>
  </head>
  <body>

    <div id="header">
      <h1>Simple CMS Admin</h1>
    </div>
    <div id="main">
      <% if !flash[:notice].blank? %>
        <div class="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <div id="content">
        <%= yield %>
      </div>
    </div>
    <div id="footer">
      <p id="copyright">&copy; lynda.com</p>
    </div>
  </body>
</html>

rails_5_essentials/exercise_files/Chapter_15/15_07/simple_cms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag('application', media: 'all') %>
    <%= javascript_include_tag('application') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_5_essentials/exercise_files/Chapter_15/15_07/simple_cms/app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple CMS<%= " | #{@page_title}" if @page_title %></title>
    <%= stylesheet_link_tag('application', :media => 'all') %>
  </head>
  <body>

    <div id="header">
      <h1>Simple CMS</h1>
    </div>

    <div id="main">

      <div id="navigation">
        <%= render(:partial => 'layouts/navigation', :locals => { :subjects => @subjects} ) %>
      </div>

      <div id="content">
        <%= yield %>
      </div>
      <div class="clear"></div>

    </div>

    <div id="footer">
      <p id="copyright">&copy; lynda.com</p>
    </div>

  </body>
</html>